const char index_web[] = "<html>"
"<head>"
"<title>"
"Home Page"
"</title>"
"<style>"
"html{background-color:#ffa07a}"
"</style>"
"</head>"
"<body>"
"<h1>Hello World</h1>"
"</body>"
"</html>"
"<script>"
"setInterval(function(){alert('javascript works!')},4e3);"
"</script>"
;
